name: crun-wasmedge
base: core20 # the base snap is the execution environment for this snap
version: "1.4.4" # just for humans, typically '1.2+git' or '1.3.2'
summary: crun with enabled wasmedge # 79 char long summary
description: |
  A fast and low-memory footprint OCI Container Runtime fully written in C.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: arm64
    run-on: arm64
  - build-on: amd64
    run-on: amd64

apps:
  crun:
    command: crun.wrapper

parts:
  crun:
    after: [wasmedge]
    plugin: autotools
    autotools-configure-parameters:
      - --with-wasmedge
      - --prefix=/usr
    build-packages:
      - curl
      - make
      - git
      - gcc
      - build-essential
      - pkgconf
      - libtool
      - libsystemd-dev
      - libprotobuf-c-dev
      - libcap-dev
      - libseccomp-dev
      - libyajl-dev
      - go-md2man
      - autoconf
      - python3
      - automake
    source: https://github.com/containers/crun.git
    source-tag: "1.4.4"
    stage-packages:
      - libyajl2

  crun-wrapper:
    source: snap/local
    plugin: dump
    stage:
      - crun.wrapper

  wasmedge:
    source: https://github.com/WasmEdge/WasmEdge.git
    source-tag: "0.9.1"
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DWASMEDGE_BUILD_TESTS=ON
    build-packages:
      - software-properties-common
      - cmake
      - libboost-all-dev
      - llvm-12-dev
      - liblld-12-dev
      - gcc
      - g++
    stage-packages:
      - libllvm12
